# Generated by Django 3.2.7 on 2021-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211028_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='project_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='schema_identifiers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='software',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
