# Generated by Django 3.2.7 on 2021-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211123_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFC_Modell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('time_stamp', models.DateTimeField(verbose_name='date published')),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('schema_identifiers', models.CharField(max_length=200, null=True)),
                ('software', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='document',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='schema_identifiers',
        ),
        migrations.RemoveField(
            model_name='document',
            name='software',
        ),
    ]
