# Generated by Django 3.2.7 on 2021-11-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211123_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifc_modell',
            name='time_stamp',
        ),
    ]
