# Generated by Django 3.2.7 on 2021-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ifc_modell_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfcModell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('time_stamp', models.DateTimeField(max_length=200, null=True)),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('schema_identifiers', models.CharField(max_length=200, null=True)),
                ('software', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IFC_Modell',
        ),
    ]
